// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rapid_Rescue.Model;

#nullable disable

namespace Rapid_Rescue.Migrations
{
    [DbContext(typeof(Rapid_RescueDbContext))]
    [Migration("20240919072853_one")]
    partial class one
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rapid_Rescue.Model.ambulance", b =>
                {
                    b.Property<int>("ambulancesid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ambulancesid"));

                    b.Property<int>("current_stastus")
                        .HasColumnType("int");

                    b.Property<int>("equipment_level")
                        .HasColumnType("int");

                    b.Property<string>("vehicle_number")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ambulancesid");

                    b.ToTable("ambulances");
                });
#pragma warning restore 612, 618
        }
    }
}
